//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF2WorkshopUrlConverter.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramStrings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KF2WorkshopUrlConverter.Core.Properties.ProgramStrings", typeof(ProgramStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://github.com/DouglasAntunes/KF2-Workshop-Collection-URL-Converter.
        /// </summary>
        internal static string AppGitHubURL {
            get {
                return ResourceManager.GetString("AppGitHubURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a KF2 Workshop Collection URL Converter.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show this message and exit..
        /// </summary>
        internal static string ArgumentDescriptionHelp {
            get {
                return ResourceManager.GetString("ArgumentDescriptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Path of a text file to export. (optional)..
        /// </summary>
        internal static string ArgumentDescriptionOutput {
            get {
                return ResourceManager.GetString("ArgumentDescriptionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The Url of the Workshop Collection. (required)..
        /// </summary>
        internal static string ArgumentDescriptionURL {
            get {
                return ResourceManager.GetString("ArgumentDescriptionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show Version info..
        /// </summary>
        internal static string ArgumentDescriptionVersion {
            get {
                return ResourceManager.GetString("ArgumentDescriptionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Missing required option u|url=.
        /// </summary>
        internal static string ErrorMissingUrlArgumentValue {
            get {
                return ResourceManager.GetString("ErrorMissingUrlArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ## END of {0} ##.
        /// </summary>
        internal static string FooterFormat {
            get {
                return ResourceManager.GetString("FooterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ### {0} ###
        ///### Coll URL: {1} ###
        ///### {2} Items | Last Query: {3} ###.
        /// </summary>
        internal static string HeaderFormat {
            get {
                return ResourceManager.GetString("HeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///{0} v{1}: {2}
        ///Use: &apos;{3} --help&apos; for more information.
        ///.
        /// </summary>
        internal static string ResponseShowError {
            get {
                return ResourceManager.GetString("ResponseShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///Usage: {0} [OPTIONS]
        ///
        ///About:
        ///Converts the URL of a Steam Workshop Collection to the format that the file &quot;PCServer-KFEngine.ini&quot; accepts.
        ///Requires URL on format like https://steamcommunity.com/sharedfiles/filedetails/?id=XXXXXXXXX... (http:// is accepted as well).
        ///## For more info or updates, go to {1}
        ///
        ///Options:.
        /// </summary>
        internal static string ResponseShowHelp {
            get {
                return ResourceManager.GetString("ResponseShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///{0} v{1}
        ///Project Page: {2}
        ///Use: &apos;{3} --help&apos; for more information.
        ///.
        /// </summary>
        internal static string ResponseShowVersion {
            get {
                return ResourceManager.GetString("ResponseShowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Success! File Saved to &quot;{0}&quot;
        ///.
        /// </summary>
        internal static string ResponseSuccessFileSaved {
            get {
                return ResourceManager.GetString("ResponseSuccessFileSaved", resourceCulture);
            }
        }
    }
}
