name: Tests

env:
  PROJECT_FOLDER: "./KF2 Workshop URL Converter/KF2 Workshop URL Converter.sln"

on:
  pull_request:
    paths:
      - "!**.*"
      - "!Images/"
      - "KF2 Workshop URL Converter/**"
      - ".github/workflows/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 3.1.201
      - name: Install Dependencies
        run: dotnet restore ${{env.PROJECT_FOLDER}}
      - name: Test
        run: dotnet test ${{env.PROJECT_FOLDER}} --nologo --no-restore --logger "console;verbosity=detailed"
